version: 2

references:
    base_image: &base_image
        circleci/golang:latest

    working_directory: &working_directory
        ~/proj

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory
        environment:
            BASH_ENV: /root/.bashrc

jobs:
  build:
      <<: *default_config
      steps:


workflows:
    version: 2
    decrypt:
        jobs:
            - build

