version: 2

references:
    base_image: &base_image
        circleci/golang:latest

    working_directory: &working_directory
        ~/proj

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory
        environment:
            BASH_ENV: /root/.bashrc

jobs:
  build:
      <<: *default_config
      steps:
          - run:
              command: openssl aes-256-cbc -d -in secret-env-cipher -k $KEY >> $BASH_ENV
              name: Decrypt repo secrets
          - run:
              command: env


workflows:
    version: 2
    decrypt:
        jobs:
            - build

