version: 2

references:
    base_image: &base_image
        circleci/golang:1.12-stretch

    working_directory: &working_directory
        ~/proj

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory
        environment:
            BASH_ENV: /root/.bashrc

    setup_environment: &setup_environment
        run:
            name: setup environment
            command: |
                cd && touch $BASH_ENV
                openssl aes-256-cbc -d -in secret-env-cipher -k $KEY >> $BASH_ENV

jobs:
  build:
      <<: *default_config
      steps:
          - *setup_environment
          - run:
              command: env


workflows:
    version: 2
    decrypt:
        jobs:
            - build

