version: 2.1

references:
    base_image: &base_image
        circleci/golang:1.12-stretch

    working_directory: &working_directory
        ~/proj

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory

    mac_config: &mac_config
        macos:
          xcode: "10.1.0"
        working_directory: *working_directory
        shell: /bin/bash --login

parameters:
    trigger_nightly:
        type: boolean
        default: false

jobs:
    build:
        <<: *default_config
        steps:
            - checkout
            - run: echo "Hello World!"


workflows:
    btd:
        jobs:
            - build
    nightly:
        jobs:
            - build
        when: << pipeline.parameters.trigger_nightly >>
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only: master
