version: 2

references:
    base_image: &base_image
        circleci/golang:1.12-stretch

    working_directory: &working_directory
        ~/proj

    encrypted_directory: &encrypted_directory
        /encrypted

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory

    setup_environment: &setup_environment
        run:
            name: setup environment
            command: |
                openssl aes-256-cbc -d -in ./encrypted/secrets_env_cipher -k "$KEY" >> $BASH_ENV

jobs:
  build:
      <<: *default_config
      steps:
          - checkout
          - *setup_environment
          - run:
              command: env


workflows:
    version: 2
    decrypt:
        jobs:
            - build

notify:
    webhooks:
        - url: $NOTIFY_WH
