references:
    working_directory: &working_directory
        ~/repo
    base_image: &base_image
        circleci/node:7.10

    default_config: &default_config
        docker:
          - image: *base_image
        working_directory: *working_directory

version: 2
jobs:
    build:
        <<: *default_config
        steps:
            - checkout
            - run:
                command: mkdir /tmp/workspace
            - run:
                command: node index.js > /tmp/workspace/random-id
                name: Generate random ID
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - random-id
            - run:
                command: node WillFailSometimes.js
                name: Non-deterministic tests
            - store_artifacts:
                path: /tmp/workspace/random-id
                destiation: random-id-artifact
            - run:
                when: always
                command: |
                    curl -X POST --header "Content-Type: application/json" -d '{
                        "build_parameters": { // optional
                          "CIRCLE_JOB": "post-run",
                          "ARTIFACT_BUILD_NUM": "$CIRCLE_BUILD_NUM"
                        }
                    }' \
                    https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME?circle-token=$CIRCLE_TOKEN

    post-run:
        <<: *default_config
        steps:
            - run:
                command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$ARTIFACT_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN
                name: pull all artifacts

workflows:
    version: 2
    trigger-2nd-job:
        jobs:
            - build:
                context: DEV-CONTEXT

