references:
    working_directory: &working_directory
        ~/repo
    base_image: &base_image
        circleci/node:7.10

    default_config: &default_config
        docker:
          - image: *base_image
        working_directory: *working_directory

version: 2
jobs:
    test-ws:
        <<: *default_config
        steps:
            - run: sleep 1m
            - attach_workspace:
                at: /tmp/workspace
            - run: echo /tmp/workspace/failed_jobs
    build:
        <<: *default_config
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run:
                command: node index.js > /tmp/workspace/random-id
                name: Generate random ID
            - run:
                command: node WillFailSometimes.js
                name: Non-deterministic tests
            - run:
                when: on_fail
                name: Store job failure
                command: echo $CIRCLE_JOB >> /tmp/workspace/failed_jobs
            - persist_to_workspace:
                root: /tmp/workspace
                paths:
                    - failed_jobs
    post-run:
        <<: *default_config
        steps:
            - run:
                command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$ARTIFACT_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN
                name: pull all artifacts

workflows:
    version: 2
    trigger-2nd-job:
        jobs:
            - build:
                context: DEV-CONTEXT
            - build:
                context: DEV-CONTEXT
            - build:
                context: DEV-CONTEXT
            - build:
                context: DEV-CONTEXT
            - build:
                context: DEV-CONTEXT
            - test_ws

