version: 2.1

references:
  base_image: &base_image
    circleci/python

  working_directory: &working_directory
    ~/proj

executors:
  default:
    docker:
      - image: *base_image
    working_directory: *working_directory

jobs:
  xdist:
    parallelism: 4
    executor: default
    steps:
      - checkout
      - run: pip install --user pytest pytest-xdist
      - run: pytest -n 4

workflows:
    btd:
      jobs:
        - xdist
