references:
    working_directory: &working_directory
        ~/repo
    base_image: &base_image
        circleci/node:7.10

    default_config: &default_config
        docker:
          - image: *base_image
        working_directory: *working_directory

    build_config: &build_config
        <<: *default_config
        steps:
            - checkout
            - attach_workspace:
                at: /tmp/workspace
            - run:
                command: node index.js > /tmp/workspace/random-id
                name: Generate random ID
            - run:
                command: |
                        if node WillFailSometimes.js ; then
                            export SUCCESS=true
                        else
                            echo $CIRCLE_JOB >> /tmp/workspace/failed_jobs
                            export SUCCESS=false
                        fi
                name: Non-deterministic tests
            - persist_to_workspace:
                root: /tmp/workspace/
                paths:
                    - ./*
            - run:
                name: Exit if job failed
                command: |
                    if $SUCCESS; then
                        exit 0
                    else
                        exit 1
                    end

version: 2
jobs:
    build1:
        <<: *build_config
    build2:
        <<: *build_config
    build3:
        <<: *build_config
    build4:
        <<: *build_config
    test_ws:
        <<: *default_config
        steps:
            - run: sleep 1m
            - attach_workspace:
                at: /tmp/workspace
            - run: cat /tmp/workspace/failed_jobs
    post-run:
        <<: *default_config
        steps:
            - run:
                command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$ARTIFACT_BUILD_NUM/artifacts?circle-token=$CIRCLE_TOKEN
                name: pull all artifacts

workflows:
    version: 2
    notify-failed-jobs:
        jobs:
            - build1:
                context: DEV-CONTEXT
            - build2:
                context: DEV-CONTEXT
            - build3:
                context: DEV-CONTEXT
            - build4:
                context: DEV-CONTEXT
            - test_ws

