version: 2

references:
    base_image: &base_image
        circleci/golang:1.12-stretch

    working_directory: &working_directory
        ~/proj

    default_config: &default_config
        docker:
            - image: *base_image
        working_directory: *working_directory

jobs:
    build:
        docker:
            - image: *base_image
        working_directory: *working_directory
        steps:
            - checkout
            - run:
                command: echo "hello"
            - run:
                command: go run main.go


workflows:
    version: 2
    btd:
        jobs:
            - build
