version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    parallelism: 2
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: test splitting
          command: circleci tests glob "*.tests.js" | circleci tests split --split-by=timings | xargs -n 1 echo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --only=dev jest-junit
      - run:
          name: Run tests with JUnit as reporter
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/results.xml"
          command: |
              TESTFILES=$(circleci tests glob "*.tests.js") | circleci tests split
              JEST_JUNIT_OUTPUT="./test-results/jest/results.xml" yarn test --maxWorkers=4 --coverage --forceExit --ci ${TESTFILES}
      - run:
          name: Sleep zzz
          command: sleep 3
      - store_test_results:
          path: test-results
    post-hold:
        docker:
            - image: circleci/node:7.10
        working_directory: ~/repo

        steps:
            - checkout:
            - run:
              name: Hold sleep
              command: sleep 3

workflows:
    version: 2
    hold-test:
        jobs:
            - build
            - hold:
                type: approval
                requires:
                    - build
            - post-hold:
                requires:
                    - hold
