version: 2.1

references:
    base_image: &base_image
        circleci/golang:1.12-stretch

    working_directory: &working_directory
        ~/proj

parameters:
    trigger_nightly:
        type: boolean
        default: false

executors:
    default:
        docker:
            - image: *base_image
        working_directory: *working_directory
    macos:
        macos:
            xcode: "10.1.0"
        working_directory: *working_directory
        shell: /bin/bash --login
    windows:
        machine:
            resource_class: windows.medium
            image: "windows-server-2019:201908-06"
            shell: bash


jobs:
    build:
        executor: windows
        steps:
            - checkout
            - run: echo "Hello World!"


workflows:
    btd:
        unless: << pipeline.parameters.trigger_nightly >>
        jobs:
            - build
    nightly:
        when: << pipeline.parameters.trigger_nightly >>
        jobs:
            - build
