version: 2.1
# 2.1 overview - https://discuss.circleci.com/t/circleci-2-1-config-overview/26057

references:
  base_image: &base_image
    circleci/golang:1.12-stretch

  working_directory: &working_directory
    ~/proj

# New in 2.1
parameters:
  trigger_e2e:
    type: boolean
    default: false

# New in 2.1
executors:
  default:
    docker:
      - image: *base_image
    working_directory: *working_directory
  macos:
    macos:
      xcode: "10.1.0"
    working_directory: *working_directory
    shell: /bin/bash --login
  windows:
    machine:
      resource_class: windows.medium
      image: "windows-server-2019:201908-06"
      shell: bash


jobs:
  echo:
    executor: macos
    steps:
      - checkout
      - run: echo "Hello World!"
      - run:
          name: Take A Screenshot
          command: screencapture screen.png
          when: always
      - store_artifacts:
          path: screen.png
  test:
    executor: default
    steps:
      - checkout
      - run: echo "Tests"
  e2e_test:
    executor: default
    steps:
      - checkout
      - run: echo "E2E Tests"
  nightly_image_build:
    executor: default
    steps:
      - checkout
      - run: echo "Build test Docker images"




# Multiple workflows defined with different triggers. `btd` triggers on commit, `e2e` triggers on an API call with the `trigger_e2e` parameter set to true, and `nightly` is triggered on a scheduled cron timer.
# https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    btd:
      unless: << pipeline.parameters.trigger_e2e >>
      jobs:
        - echo
        - test
    e2e:
      when: << pipeline.parameters.trigger_e2e >>
      jobs:
        - echo
        - e2e_test
    nightly:
      jobs:
        - echo
            context: TEST
        - test
        - nightly_image_build
      triggers:
        - schedule:
            cron: "18 25 * * *"
            filters:
              branches:
                only:
                  - master
                  - staging
