version: 2.1

orbs:
    disable-rerun: johnstonjacob/disable-rerun@0.0.5

executors:
    python:
        docker:
            - image: circleci/python:3.7.2

jobs:
    rerun-check:
        executor: python
        steps:
            - disable-rerun/check-build-ran
            - disable-rerun/mark-build-ran

workflows:
    version: 2.1
    hold-test:
        jobs:
            - rerun-check:
                context: ORB-PUBLISHING
